<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Sklep.aspx.cs" Inherits="ASPPAB.Zawodnicy" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">

        .auto-style2 {
            height: 75px;
        }
        .auto-style9 {
            margin-left: 20px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="prod_id" DataSourceID="SqlDataSource1" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="prod_id" HeaderText="prod_id" ReadOnly="True" SortExpression="prod_id" />
                <asp:BoundField DataField="prod_nazwa" HeaderText="prod_nazwa" SortExpression="prod_nazwa" />
                <asp:BoundField DataField="prod_adres" HeaderText="prod_adres" SortExpression="prod_adres" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SRBDConnectionString %>" DeleteCommand="DELETE FROM [Producent] WHERE [prod_id] = @prod_id" InsertCommand="INSERT INTO [Producent] ([prod_id], [prod_nazwa], [prod_adres]) VALUES (@prod_id, @prod_nazwa, @prod_adres)" SelectCommand="SELECT * FROM [Producent]" UpdateCommand="UPDATE [Producent] SET [prod_nazwa] = @prod_nazwa, [prod_adres] = @prod_adres WHERE [prod_id] = @prod_id">
            <DeleteParameters>
                <asp:Parameter Name="prod_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="prod_id" Type="Int32" />
                <asp:Parameter Name="prod_nazwa" Type="String" />
                <asp:Parameter Name="prod_adres" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="prod_nazwa" Type="String" />
                <asp:Parameter Name="prod_adres" Type="String" />
                <asp:Parameter Name="prod_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <div class="auto-style2">
            <asp:Label ID="Label1" runat="server" Text="Nazwa:"></asp:Label>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            <asp:Label ID="Label2" runat="server" Text="Adres:"></asp:Label>
            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
            <asp:Button ID="Button14" runat="server" OnClick="Button14_Click" Text="Dodaj" />
            <asp:Button ID="Button15" runat="server" CssClass="auto-style9" OnClick="Button15_Click" Text="Odswiez" Width="129px" />
        </div>
        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="pro_id" DataSourceID="SqlDataSource2">
            <Columns>
                <asp:BoundField DataField="pro_id" HeaderText="pro_id" ReadOnly="True" SortExpression="pro_id" />
                <asp:BoundField DataField="prod_id" HeaderText="prod_id" SortExpression="prod_id" />
                <asp:BoundField DataField="pro_nazwa" HeaderText="pro_nazwa" SortExpression="pro_nazwa" />
                <asp:BoundField DataField="pro_cena" HeaderText="pro_cena" SortExpression="pro_cena" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:SRBDConnectionString %>" DeleteCommand="DELETE FROM [Produkt] WHERE [pro_id] = @pro_id" InsertCommand="INSERT INTO [Produkt] ([pro_id], [prod_id], [pro_nazwa], [pro_cena]) VALUES (@pro_id, @prod_id, @pro_nazwa, @pro_cena)" SelectCommand="SELECT * FROM [Produkt] WHERE ([prod_id] = @prod_id)" UpdateCommand="UPDATE [Produkt] SET [prod_id] = @prod_id, [pro_nazwa] = @pro_nazwa, [pro_cena] = @pro_cena WHERE [pro_id] = @pro_id" OnSelecting="SqlDataSource2_Selecting">
            <DeleteParameters>
                <asp:Parameter Name="pro_id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="pro_id" Type="Int32" />
                <asp:Parameter Name="prod_id" Type="Int32" />
                <asp:Parameter Name="pro_nazwa" Type="String" />
                <asp:Parameter Name="pro_cena" Type="String" />
            </InsertParameters>
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="prod_id" PropertyName="SelectedValue" Type="Int32" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="prod_id" Type="Int32" />
                <asp:Parameter Name="pro_nazwa" Type="String" />
                <asp:Parameter Name="pro_cena" Type="String" />
                <asp:Parameter Name="pro_id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <div class="auto-style2">
            <asp:Label ID="Label3" runat="server" Text="ID_producenta:"></asp:Label>
            <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
            <asp:Label ID="Label4" runat="server" Text="Nazwa"></asp:Label>
            <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
            <asp:Label ID="Label5" runat="server" Text="Cena:"></asp:Label>
            <asp:TextBox ID="TextBox7" runat="server"></asp:TextBox>
            <asp:Button ID="Button18" runat="server" OnClick="Button18_Click" Text="Dodaj" />
            <asp:Button ID="Button17" runat="server" CssClass="auto-style9" OnClick="Button15_Click" Text="Odswiez" Width="129px" />
        </div>
    </form>
</body>
</html>
